FROM python:3.9.0

WORKDIR /home/

RUN echo "testing"

RUN git clone https://github.com/matt700395/LKLK.git

WORKDIR /home/LKLK/

RUN python -m pip install --upgrade pip

RUN pip install -r requirements.txt

RUN pip install gunicorn

RUN echo "SECRET_KEY= django-insecure-$9ej%!yr-5%hb(bubw8bw3hc*y$564&!ch&64g2dyy0e+u^_r7" > .env

RUN python manage.py migrate

EXPOSE 8000

CMD ["gunicorn", "pragmatic.wsgi" , "--bind", "0.0.0.0:8000"]